#include <vector>
extern double xBeamPos;
extern double yBeamPos;
extern int fibreStart0;
extern int  NPhotAct;
extern int  NPhotFib;
extern int  NPhotFib2;
extern int  NPhotFib3;
extern int  NPhotFib4;
extern int fibre0;
extern int fibre1;
extern int fibre2;
extern int fibre3;
extern double EOpt_0;
extern double EOpt_1;
extern double EOpt_2;
extern double EOpt_3;
extern int nPhotonsForTiming;
extern std::vector<float> time_vector;
